- hosts: all
  become: yes
  tasks:
    - name: Install Nginx and PHP
      apt:
        name:
          - nginx
          - php-fpm
          - php-mysql
          - php-dom
          - php-simplexml
          - php-curl
          - php-intl
          - php-zip
          - php-xml
          - php-gd
          - php-imagick
          - php-cli
          - php-dev
          - php-imap
          - php-soap
          - php-mbstring
        state: latest
        update_cache: yes

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: true
