- hosts: all
  become: yes
  vars:
    db_endpoint: "{{ lookup('env', 'DB_ENDPOINT') }}"
    db_username: "{{ lookup('env', 'DB_USERNAME') }}"
    db_password: "{{ lookup('env', 'DB_PASSWORD') }}"
  tasks:
    - name: Install Nginx and PHP
      apt:
        name:
          - nginx
          - php-fpm
          - php-mysql
          - php-dom
          - php-simplexml
          - php-curl
          - php-intl
          - php-zip
          - php-xml
          - php-gd
          - php-imagick
          - php-cli
          - php-dev
          - php-imap
          - php-soap
          - php-mbstring
        state: latest
        update_cache: yes

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Download PrestaShop
      get_url:
        url: https://download.prestashop.com/download/releases/prestashop_1.7.8.0.zip
        dest: /var/www/html/prestashop_1.7.8.0.zip
        mode: '0644'

    - name: Unzip PrestaShop
      unarchive:
        src: /var/www/html/prestashop_1.7.8.0.zip
        dest: /var/www/html/
        remote_src: yes
        creates: /var/www/html/prestashop

    - name: Move PrestaShop files to web root
      command: mv /var/www/html/prestashop/* /var/www/html/

    - name: Remove downloaded and extra PrestaShop directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/www/html/prestashop_1.7.8.0.zip
        - /var/www/html/prestashop

    - name: Set ownership of web files
      file:
        path: /var/www/html/
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: Set permissions on web files
      file:
        path: /var/www/html/
        state: directory
        mode: '0755'
        recurse: yes

    - name: Configure PrestaShop database settings
      template:
        src: templates/ps_settings.inc.php.j2
        dest: /var/www/html/config/settings.inc.php
        owner: www-data
        group: www-data
        mode: '0644'