name: Playbook execution

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "eu-central-1"
  ANSIBLE_HOST_KEY_CHECKING: False

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Switch environment (blue or green)'
        required: true
        default: 'blue'

jobs:
  run-ansible:
    runs-on: ubuntu-latest
    name: Run playbook

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Execute playbook
        run: ansible-playbook ./ansible/switch_traffic.yml -e "current_environment=${{ github.event.inputs.environment }}"
        working-directory: ./ansible